name: ToXiiCSellAll
version: 1.0.0
main: net.toxiic.sellall.SellAll
description: Sell all items with the prices obtained through BossShop
author: ToXiiC
depend: [BossShop, Vault]
softdepend: [ToXiiCxMultiplier]
commands:
    sellall:
      description: Sell all items sell-able in your rank shop.
      usage: /<command>
    sall:
      description: Sell all items sell-able in your rank shop without a GUI!
      usage: /<command>